### ISSUE TITLE
Requirements: tensorflow >= 2.1

### ISSUE THREAD

**Issue by caglorithm** [jajcayn/pygpso#16]
Requires `tensorflow >= 2.1` which should be stated in the `requirements.txt`

**Comment by jajcayn** [comment]
this should be handled by `GPFlow` dependency since GPFlow depends on `tensorflow>=2.0`... did you have any problems installing the package because of this? When I install it in a clean virtual environment, it works, `tensorflow` is correctly installed as `GPFlow` dependency

**Comment by caglorithm** [comment]
I installed using the `requirements.txt` and apparently my `GPFlow` didn't come with that dependency.... 🤔

**Comment by jajcayn** [comment]
when installing the package within anaconda (or miniconda) environment, the tensorflow is not installed. I believe the culprit is that conda-forge as of now contains tensorflow 2.0 and not 2.1 yet, so it doesn't do anything.. however specifying it in the requirements would work, because then `conda` will fall-back to `pip`
